merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.bands_list, name='bands'),
    path('bands/<int:id>/', views.bands_detail, name='band-detail'),
    path('bands/add/', views.band_add, name='band-add'),
    path('bands/<int:id>/update/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('listings/', views.listings, name='listings'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_add, name='listing-add'),
    path('listings/<int:id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-send/', views.email_send, name='email'),
]

merchex/listings/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.
class Band(models.Model):

    def __str__(self):
        return f'{self.name}'

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)


class Listing(models.Model):

    def __str__(self):
        return f'{self.title}'

    class Type(models.TextChoices):
        RECORDS = 'Disques'
        CLOTHING = 'Vetements'
        POSTERS = 'Affiches'
        MISCELLANEOUS = 'Divers'

    title = models.fields.CharField(max_length=200)
    description = models.fields.CharField(max_length=400)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    type = models.fields.CharField(choices=Type.choices, max_length=20)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

from listings.models import Band
from listings.models import Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def bands_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def bands_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html', {'band': band})


def about(request):
    return render(request, 'listings/about.html')


def listings(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': listings})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email')
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form': form})


def email_send(request):
    return render(request, 'listings/email.html')


def band_add(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_add.html', {'form': form})


def listing_add(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request, 'listings/listing_add.html', {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request, 'listings/band_update.html', {'form': form})


def listing_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, 'listings/listing_update.html', {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        messages.success(request, 'Le groupe ' + band.name + ' a bien été supprimé :)')
        return redirect('bands')
    return render(request, 'listings/band_delete.html', {'band': band})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        messages.success(request, 'Le produit ' + listing.title + ' est bien supprimé :)')
        return redirect('listings')
    return render(request, 'listings/listing_delete.html', {'listing': listing})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Page de présentation</h1>
{% endblock %}

merchex/listings/templates/listings/band_add.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active }}</li>
    <li>{{ band.official_homepage }}</li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">[modifier]</a> -
<a href="{% url 'band-delete' band.id %}">[supprimer]</a> -
<a href="{% url 'bands' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div>
    {{ message }}
</div>
{% endfor %}
{% endif %}
<h1>Groupes</h1>
<ul>
    {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[modifier]</a>
        - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Modifier un groupe</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
<head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css'  %}" />
</head>
<body>

  <nav>
      <a href="{% url 'bands' %}">Groupes</a>
      <a href="{% url 'listings' %}">Produits</a>
      <a href="{% url 'about' %}">Qui sommes-nous ?</a>
      <a href="{% url 'contact' %}">Contact</a>
      <a href="{% url 'band-add' %}">Ajouter un groupe</a>
   </nav>

{% block content %}{% endblock %}

</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Contactez-nous :</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/email.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Email envoyé !</h1>
{% endblock %}

merchex/listings/templates/listings/listing_add.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau produit dérivé</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le produit</h1>

<p>Etes-vous sûr de vouloir supprimer le produit : {{ listing.title }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ listing.title }}</h2>

<ul>
    <li>Type : {{ listing.get_type_display }}</li>
    <li>Année : {{ listing.year }}</li>
    <li>Groupe : {{ listing.band }}</li>
</ul>

<p>Description: {{ listing.description }}</p>

<a href="{% url 'listing-update' listing.id %}">[modifier]</a> -
<a href="{% url 'listing-delete' listing.id %}">[supprimer]</a> -
<a href="{% url 'listings' %}">Retour à tous les produits</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div>
    {{ message }}
</div>
{% endfor %}
{% endif %}
<h1>Voici la liste des titres :</h1>
<ul>
    {% for listing in listings%}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[modifier]</a>
        - <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Modifier un produit dérivé</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}